config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'lifetips#index'
  resources :lifetips
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lifetip.rb
class Lifetip < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lifetips_controller.rb
class LifetipsController < ApplicationController

def index
   @lifetips = Lifetip.all 
end

def new 
   @lifetip = Lifetip.new 
end 

def create
    Lifetip.create(lifetip_params)
    redirect_to root_path
  end

  private

  def lifetip_params
    params.require(:lifetip).permit(:name, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lifetips_helper.rb
module LifetipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lifetips</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'LIfeTips', '#', class: 'navbar-brand' %>
</li>
       <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">

          <li class="nav-item">
            <%= link_to 'New LifeTip', new_lifetip_path, class: 'nav-link' %>
          </li>
          </li>
        </ul>
        </form>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lifetips/index.html.erb
<% @lifetips.each do |lifetip| %>
<div class="booyah-box col-10 offset-1">
  <div>
    <h1><%= lifetip.name %></h1><br />
    <p><%= lifetip.description %></p><br /><br />
  </div>
</div>
  <hr />
<% end %>

app/views/lifetips/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Lifetip</h1>
  <%= simple_form_for @lifetip do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <br />
       <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>